import 'package:flutter/material.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedVectorStroke41Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedVectorStroke61Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedVectorStroke51Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedCardHorizontal11Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedLowStockWidget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedProductWidget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedCardHorizontal21Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedHomeWidget1.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedVectorStroke53Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedVectorStroke52Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedRectangle30151Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedContainer1Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/Generated10Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedStockwarningWidget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedWelcomeWidget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedVectorStroke21Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedLogo1Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedVectorStroke54Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedTransactionsWidget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedGooglenameWidget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/Generated4Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedVectorStroke62Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedCardHorizontal22Widget.dart';
import 'package:flutterapp/zara_flut1app/generatediphone11promax1widget/generated/GeneratedCardHorizontal1Widget.dart';

/* Frame iPhone 11 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 59.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 18.649993896484375,
                top: 15.649999618530273,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedLogo1Widget(),
              ),
              Positioned(
                left: 167.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 48.0,
                child: GeneratedHomeWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 48.0,
                child: GeneratedWelcomeWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 23.0,
                child: GeneratedGooglenameWidget(),
              ),
              Positioned(
                left: 218.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 126.0,
                child: GeneratedCardHorizontal11Widget(),
              ),
              Positioned(
                left: 285.0,
                top: 188.39999389648438,
                right: null,
                bottom: null,
                width: 46.0,
                height: 77.87000274658203,
                child: Generated4Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 126.0,
                child: GeneratedCardHorizontal1Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 188.39999389648438,
                right: null,
                bottom: null,
                width: 72.0,
                height: 77.87000274658203,
                child: Generated10Widget(),
              ),
              Positioned(
                left: 162.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 22.75,
                height: 28.0,
                child: GeneratedVectorStroke21Widget(),
              ),
              Positioned(
                left: 365.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 22.75,
                height: 28.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 45.0,
                child: GeneratedLowStockWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 334.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 23.0,
                child: GeneratedStockwarningWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 394.0,
                height: 119.0,
                child: GeneratedCardHorizontal21Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 507.0,
                right: null,
                bottom: null,
                width: 394.0,
                height: 119.0,
                child: GeneratedCardHorizontal22Widget(),
              ),
              Positioned(
                left: 172.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 58.95082092285156,
                child: GeneratedContainer1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 805.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 96.0,
                child: GeneratedRectangle30151Widget(),
              ),
              Positioned(
                left: 84.0,
                top: 838.0,
                right: null,
                bottom: null,
                width: 22.947729110717773,
                height: 21.950000762939453,
                child: GeneratedVectorStroke41Widget(),
              ),
              Positioned(
                left: 198.0,
                top: 837.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedVectorStroke51Widget(),
              ),
              Positioned(
                left: 211.0,
                top: 837.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedVectorStroke52Widget(),
              ),
              Positioned(
                left: 197.0,
                top: 849.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 10.0,
                child: GeneratedVectorStroke53Widget(),
              ),
              Positioned(
                left: 210.0,
                top: 849.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 10.0,
                child: GeneratedVectorStroke54Widget(),
              ),
              Positioned(
                left: 320.0,
                top: 837.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 10.0,
                child: GeneratedVectorStroke61Widget(),
              ),
              Positioned(
                left: 343.0,
                top: 859.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 10.0,
                child: GeneratedVectorStroke62Widget(),
              ),
              Positioned(
                left: 70.0,
                top: 869.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 14.0,
                child: GeneratedHomeWidget1(),
              ),
              Positioned(
                left: 172.0,
                top: 868.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 15.0,
                child: GeneratedProductWidget(),
              ),
              Positioned(
                left: 288.0,
                top: 868.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 18.0,
                child: GeneratedTransactionsWidget(),
              )
            ]),
      ),
    ));
  }
}
